project:
  type: website
  output-dir: docs

website:
  
  navbar:
    logo: figuras/ec.png
    logo-alt: "EC"
    background: primary
    search: true
    left:
      - text: "Início"
        file: pagina_inicial.qmd
      - text: "Projetos"
        file: projects.qmd
      - text: "Disciplinas"
        menu:
        - text: "Consultoria Estatstica"
          file: dis_consultoria.qmd
      - text: "CV"
        file: cv.qmd
      - text: "Contato"
        file: contact.qmd
    right:
      - icon: github
        href: https://github.com/eloisacost
      - icon: linkedin
        href: www.linkedin.com/in/eloísa-s-costa-361400178

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Pesquisa"
        contents:
          - projects.qmd
      

format:
  html:
    theme: 
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss]
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true




