---
title: "Curriculum Vitae"
quarto renderquarto renderformat: 
  html: default
  pdf: default
---

## Identificação

**Nome:** Eloísa da Silva Costa  

**Lattes:** [https://lattes.cnpq.br/6314409668021150](http://lattes.cnpq.br/)

**Linkedin:** [https://www.linkedin.com/in/eloísa-s-costa-361400178](https://www.linkedin.com/) 

**Email:** eloisa.costa@aluno.uepb.edu.br

## Formação Acadêmica

### Graduação

## 🎓 Formação Acadêmica

**2026.2: Bacharelado em Estatística** Universidade Estadual da Paraíba (UEPB).  


## Experiência e Projetos Aplicados

**2025 - atual: Membro de Projeto de Extensão** \
*Projeto Incluir – UEPB: Acompanhamento e Permanência de Estudantes Cotistas* \
Orientadora: Profa. Dra. Ana Patrícia Bastos Peixoto  
- Atuação em projetos de suporte, análise e acompanhamento de dados voltados para a permanência estudantil.

**Participante de Projeto de Extensão** \
*Atividades de Ensino de Estatística como Extensão no Âmbito da UEPB* \
Coordenador: Prof. Dr. Tiago Almeida de Oliveira  
- Desenvolvimento de materiais, suporte pedagógico e aplicação de conceitos estatísticos práticos para a comunidade acadêmica.

**Desenvolvedora de Projetos Estatísticos Acadêmicos** \
*Projetos Analíticos Aplicados – UEPB* \
- **Séries Temporais:** Modelagem econométrica (SARIMA e ARIMA) para projeção de vendas futuras.  
- **Análise Multivariada:** Aplicação de Análise de Clusters para identificar padrões complexos e segmentação de dados multidimensionais.

**2026: Desenvolvedora de Projeto em Consultoria Estatística** \
*Sistema de Previsão de Churn em Telecomunicações* \
Equipe: Richard Matheus A. da Silva e Túlio Herculano  
- Desenvolvimento de uma solução analítica preditiva (Regressão Logística em Python) para identificar precocemente o risco de cancelamento de clientes.
- Construção de aplicação web estruturada em microsserviços (API e Dashboard interativo) e realização de deploy em nuvem utilizando FastAPI, Streamlit, Docker e Render.

## Competências Técnicas e Cursos

- **Linguagens e Ferramentas:** R (RStudio, `dplyr`, `ggplot2`), Python (Pandas, Scikit-learn), Excel (Avançado), Git, GitHub, Quarto, R Markdown.  
- **Modelagem Avançada e Machine Learning:** Machine Learning (Regressão Logística), Séries Temporais (ARIMA/SARIMA e ETS), Análise Multivariada (Clusters K-means e Hierárquicos), Econometria.  
- **Desenvolvimento e Deploy:** Criação de APIs (FastAPI), Dashboards Interativos (Streamlit), Conteinerização (Docker) e Deploy em Nuvem (Render).
- **Cursos Complementares:** 
  - Curso Excel COMPLETO do Básico ao Avançado – Udemy (2019).
  - Mini-curso em Relatórios Dinâmicos usando R Markdown (2018).

---

